title: Adam Harris
description: Web Developer
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title/
category_dir: category
paginate: 5
siteurl: http://www.adamwadeharris.com
baseurl:
disqus_shortname: adamwadeharris
google_analytics_code: UA-31980509-3
google_analytics_url: adamwadeharris.com
exclude: [bower.json, README.md]
lcb: "{"
rcb: "}"
prose:
  media: "assets/uploads"
  siteurl: "http://www.adamwadeharris.com"
defaults:
  - scope:
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      type: pages
    values:
      layout: default
