title: Adam Harris
description: Web Developer
markdown: kramdown
highlighter: pygments
permalink: /:title/
category_dir: category
paginate: 5
siteurl: http://www.adamwadeharris.com
baseurl:
disqus_shortname: adamwadeharris
