title: Adam Harris
description: Web Developer
markdown: kramdown
highlighter: pygments
permalink: /:title/
category_dir: category
paginate: 5
siteurl: http://www.adamwadeharris.com
baseurl:
disqus_shortname: adamwadeharris
google_analytics_code: UA-31980509-3
google_analytics_url: adamwadeharris.com
exclude: [bower.json]
