title: Adam Harris
description: Web Developer
markdown: kramdown
pygments: true
permalink: /:title/
category_dir: category
paginate: 5
url: http://www.adamwadeharris.com
disqus_shortname: adamwadeharris